### ISSUE TITLE
Leveraging Issue Labels to be welcoming and accessible to new contributors

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/operations#15]
At 1/10 Office Hours, we had a great discussion on using Issue Labels to be inviting and accessible to new contributors. This Issue can be a platform to extend that discussion. 

Some of the notes from our discussion include: 
* There's variance in the degree of difficulty on "Contributions Welcome" issues. Being more explicit about the degree of difficulty will help new contributors find issues that match their skill level and familiarity with the project. 
* We like the idea of, at minimum, providing a label that conveys that a particular issue would be a good first contribution, eg "Good for Beginners" or "Good First Issue". 
* If we have a "Good First Issue" label, do we also need a "Contributions Welcome" label? 
* One potential ambiguity in the "Contributions Welcome" label is that it sort of implies that other Issues are not welcome to contributions? Does an Issue without a Contributions Welcome label signify that contributors shouldn't try to take it on?

**Comment by BrianLitwin** [comment]
Another consideration (that [@Huddie](https://github.com/Huddie) suggested to me) is that there is this banner on the Issues tab that says: "Label issues and pull requests for new contributors", with links to "Help Wanted" and "Good First Issue" labels. It doesn't matter whether your project actively uses those labels or not, GitHub will link to a list of all your Issues with those labels, and the lists will be empty if your project doesn't use them. 

Ie GitHub seems to want to formalize the way projects label issues for new contributors.

**Comment by teamdandelion** [comment]
I renamed the SourceCred "contributions welcome" label to "good first issue", and did some auditing of the issues posted there. @BrianLitwin could you check my work and see if it's in a good state? (e.g. does that welcome bar in GitHub work as expected; I'm not sure where to find it.)

**Comment by BrianLitwin** [comment]
Lgtm!

Referring to this banner/bar at the top of the Issues tab: 
<img width="1060" alt="screenshot 2019-01-14 20 36 31" src="https://user-images.githubusercontent.com/26695477/51152949-3357b080-183c-11e9-9a01-bf28916849b4.png">

**Comment by teamdandelion** [comment]
Great. Closing this issue.
