### ISSUE TITLE
Suggestion: specify a timeframe for responding to Pull Requests

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/operations#16]
This is a light suggestion, but something I liked from one of Mozilla's repos' [contributing guides] is the last sentence on their guide stating: "We aim to respond to all review requests within two business days." 

From a contributors perspective, it's really nice to have some expectation about when your pull request will be acknowledged. Otherwise, you're kind of just anxiously watching your notifications.  There are plenty of repos where the maintainers simply don't have time to respond to PRs that quickly, so it's nice as a contributor to know upfront. 

From a project management perspective, it feels like a nice way to be deliberate/intentional about prioritizing the relationship with contributions/contributors. 

A semi-important distinction is that they're not promising to review your pr in two days, just to respond to it. Another semi-important distinction is that they're not actually *promising* anything, just stating that their *goal* is to respond within two business days. 

Not suggesting two days is the right timeframe to choose; just that being clear on this point is helpful for contributors and maintainers. 

[contributing guides]: https://github.com/mozilla-lockbox/lockbox-ios/blob/master/docs/contributing.md

**Comment by teamdandelion** [comment]
Thanks for the suggestion. I'm open to it, although I'm also inclined to take a "wait and see" approach, and see as the project scales up, how feasible it is to maintain the two-day response timeframe. So far I think we've consistently responded to PRs within a few business days. @wchargin any thoughts?
