### ISSUE TITLE
Is this repo named appropriately? 

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/operations#17]
There was some discussion at [1-24 Office Hours] that perhaps we do a lot of Logistics in our Mission repo. For reference, @wpank suggested that [IPFS] and [Ethereum] have good project management repos. 

[1-24 Office Hours]: https://github.com/sourcecred/mission/issues/13
[IPFS]: https://github.com/ipfs
[Ethereum]: https://github.com/ethereum

**Comment by wpank** [comment]
I think a dedicated place for project management can help keep things a bit more organized. 

Examples of other open source projects with a dedicated project management repository:

- [Ethereum](https://github.com/ethereum/pm)

- [Ethereum 2.0](https://github.com/ethereum/eth2.0-pm)

- [Grin (mimblewimble)](https://github.com/mimblewimble/grin-pm)

- [IPFS](https://github.com/ipfs/team-mgmt)

Some of these have nice templates for formalizing notes out of public calls/discussions.

**Comment by teamdandelion** [comment]
Maybe I'll take the page from ethereum's book and just rename this repo to `pm`. Any objections?

**Comment by wpank** [comment]
Sounds good to me :+1:

**Comment by teamdandelion** [comment]
Done!
