### ISSUE TITLE
SourceCred / CodeBuddies walkthrough

### ISSUE THREAD

**Issue by teamdandelion** [sourcecred/operations#2]
This thread is for organizing/planning the SourceCred / [Code Buddies] code walkthrough.

The plan is to have an hourlong video walkthrough of SourceCred. Here's the agenda*

1. **Why SourceCred Exists** 
    - Why attributing credit is important
2. **Demo of SourceCred on a few different repositories** 
3. **SourceCred's general design**
    - Overview of PageRank algorithm
    - The Graph
    - The Explorer
    - The Plugin System
    - The Website
4. **High-level code walkthrough** 
5. **Setup instructions**
6. **Discussion of 3 Open Issues (tbd)**
    - each with a walkthrough of the code files impacted

We still need to decide on the time. I propose any of the following timeslots:
- [x] Monday December 10, at 10am PT (1pm ET)
- [ ] Tuesday December 11, at 11am PT (2pm ET)
- [ ] Wednesday December 12, at 9am PT (12pm ET)

If you're interested in attending, please reply with which date is your
favorite, and whether any don't work at all for you. My vote is for Tuesday. :)

[Code Buddies]: https://codebuddies.org/

* Thanks to @lpatmo for helping set this up, and for suggestions on the agenda

**Comment by julianjohannesen** [comment]
I can make all of those work, but would prefer Monday at 10 PT / 1 ET.

**Comment by nickisobrien** [comment]
Monday has my vote as well!

**Comment by lpatmo** [comment]
Sounds like Monday it is! @decentralion Do you want to create a Zoom link (this means the recording will be saved locally to your desktop, which you can share later via Dropbox) or do you want one of us to? Or would you prefer another hangout platform?

**Comment by teamdandelion** [comment]
Zoom sounds good. Here's my Zoom link: https://protocol.zoom.us/my/dandelion

Look forward to seeing you all on Monday, Dec 10 at 10am PT!

**Comment by lpatmo** [comment]
Thanks @decentralion! I can schedule the hangout on CB tomorrow, or let you do the honors. (Below is a screenshot of me filling out the details -- let me know if you want the title/description adjusted.)

![image](https://user-images.githubusercontent.com/4512699/49571356-da683480-f8ed-11e8-8fe9-23c4c9f7963b.png)

**Comment by coderwithattitude** [comment]
unfortunately wont be able to attend, can you please record the video session and share?

**Comment by teamdandelion** [comment]
@lpatmo Please do schedule it! I'll ask that the description/summary change to:

"SourceCred is anchored by a long-term goal: we want open-source contributors to earn a living from their work. We this requires a quantitative system for assigning credit in projects, so we're working on a PageRank-based credit attribution system."

Then the GitHub link and agenda. :) 

@coderwithattitude will do!

**Comment by lpatmo** [comment]
Awesome, scheduled! https://codebuddies.org/hangout/AQ6ioEKXY6DnCiyES

**Comment by teamdandelion** [comment]
Here's a project board with [issues that I'm going to discuss][1] in the walkthrough.

[1]: https://github.com/sourcecred/sourcecred/projects/1

**Comment by teamdandelion** [comment]
Here's an invitation link for the meeting: https://protocol.zoom.us/j/642860193

**Comment by teamdandelion** [comment]
Thanks @julianjohannesen @swapagarwal @hendersonjames @moskalyk and @nickisobrien for attending!

**Comment by teamdandelion** [comment]
@lpatmo I sent you a Dropbox link with the recording, would love your help getting it polished+available online

**Comment by anthrocypher** [comment]
Hey y'all! I couldn't make this, but would love to check out the recording as well @decentralion.

**Comment by nickisobrien** [comment]
Hi @decentralion my bad, here I am!

**Comment by BrianLitwin** [comment]
This [Youtube vid](https://www.youtube.com/watch?v=pt8KawL24wU) of the walk-through is *so* awesome and very welcoming to new contributions! Soft suggestion that y'all should put it on the project Readme somewhere. Great stuff!

**Comment by teamdandelion** [comment]
Will do!

**Comment by teamdandelion** [comment]
@BrianLitwin i made this PR: https://github.com/sourcecred/sourcecred/pull/1024
Want to check it over for typos and such? :)
