### ISSUE TITLE
Choose a logo for SourceCred

### ISSUE THREAD

**Issue by teamdandelion** [sourcecred/operations#5]
This is a port of a logo design thread that started internally to Protocol Labs at https://github.com/protocol/design/issues/126.

## My first post:
SourceCred needs a logo! :smiley: 

The [SourceCred design brief](https://docs.google.com/document/d/1hOI4ZP4Uosmn6D6HCdrGzT4CQ22ASAq-KrSbv7g591c/edit#heading=h.95q4vei5rdmp) has details, including an overview of SourceCred and the visual language/metaphors I have in mind for the brand. There's a section [on the logo in particular](https://docs.google.com/document/d/1hOI4ZP4Uosmn6D6HCdrGzT4CQ22ASAq-KrSbv7g591c/edit#heading=h.qareyj7and1b).

**Comment by teamdandelion** [comment]
## Reply from @akrych

Hello @decentralion ! :D 

I made for You first round of logo sketch and brand look and feel for SourceCred. I have analyzed all the pros and cons  - and I think that we should stick to the old symbol. As you will see on Stylescapes (It is a design deliverable that helps present a visual language direction of a project. It consists of fonts, colors, logo etc.) I was trying to explore some new approach to the symbol, but after all I decided the simple old sign is the best and we should stick to it.  To refresh it and make it more bright, bold and manful I add to it new contrast colors.

We should also bear in mind the bigger picture of all Brand (SourceCred&SourceGrain)., so I would like to stick with green with SourceCred and Yellow with SourcGrain. As we agreed -  both can by symbolize by ecosystem, nature, growth, and sunlight - so this 2 colors will be a natural choice. They will be also correlated with each other as green for nature and yellow for sun - so the link between SourceCred and SourceGrain will be natural (!) and easy to see. 

In the light of the above, the next board that I will present will be SourcGrain with yellow as the main color in the palette. So.. Enjoy and let me know what do you feel and think about it! :D 👍 

https://projects.invisionapp.com/boards/XP3RE8WYMRG/

(The project is in inVision app - you can comment it there if you like, after click on chosen picture. 
Let me know if you are not familiar with inVision and needs help)

![image](https://user-images.githubusercontent.com/1400023/49664530-06c3a400-fa07-11e8-833b-06928ba6f856.png)
![image](https://user-images.githubusercontent.com/1400023/49664552-17741a00-fa07-11e8-8ebf-a55f0d947a8f.png)
![image](https://user-images.githubusercontent.com/1400023/49664574-222eaf00-fa07-11e8-87b6-bbffcfec8319.png)

really-by: @akrych

**Comment by teamdandelion** [comment]
Hi @akrych! Thank you for the logo exploration! Seeing it has helped me learn a lot about what I want our branding to communicate. 

![image](https://user-images.githubusercontent.com/1400023/49183668-5375f380-f312-11e8-873a-c84558adc607.png)
This logo, with its bold edges and electric green, strikes me as "cool", "edgy", and "techie". However, I'm realizing that I actually want SourceCred's branding to communicate rather different values: humility, empathy, inclusivity. I'd also like the nature connection to come through very clearly. (Humility is important because assigning scores to people's work is very sensitive, so SourceCred mustn't seem arrogant in doing so.)

To that end, I think we should move away from using the ¤ symbol, and instead orient on nature-inspired imagery. I spent some time exploring potential logos with a friend and here's what we came up with: 
![image](https://user-images.githubusercontent.com/1400023/49182671-c29e1880-f30f-11e8-9424-bffc54c9966b.png)

My favorite is the sun-with-sprout design, like this one:
![image](https://user-images.githubusercontent.com/1400023/49182807-1b6db100-f310-11e8-9ba9-a2cccecd52a4.png)

I love the sprout as a symbol. It's humble, but also one full of potential and optimism. The sun then fits in as a supporting role, clearly emphasizing the connection between sunlight and growth. 

Having a yellow and green theme then plays well, with green in the foreground, yellow in the background. For SourceGrain, we could invert it, with a golden grain symbol in the foreground, and leafy greens in the background. 

The almond-like shape made by the suns rays could be reminiscient of a seed, or the shape of a leaf... or we could just change it so that it fits more directly into a hexagon. :smile:

For color choices, maybe we can riff on the following boards:
![image](https://user-images.githubusercontent.com/1400023/49183104-e4e46600-f310-11e8-8a61-45a02082993b.png)

![image](https://user-images.githubusercontent.com/1400023/49183152-08a7ac00-f311-11e8-8138-bceb6fff4ae7.png)
 
![image](https://user-images.githubusercontent.com/1400023/49183173-12c9aa80-f311-11e8-8731-bd33953bbc60.png)

What do you think of these ideas? Would you try another board using the sun-and-sprout theme?

**Comment by teamdandelion** [comment]
## Reply from @flyingzumwalt

The shift away from edgy/cool in order to preserve a tone of humility sounds right to me. I’m not sure about the natural tones for color palette — might not pop — but I’m curious to see what you come up with.  

Other terms to consider adding to the brand treatment: interdependence, connectedness, reliance, reinforcement, acknowledgement, appreciation, flow

really-by: @flyingzumwalt

**Comment by teamdandelion** [comment]
Reply from @akrych

I have for you some new ideas: https://projects.invisionapp.com/boards/DX3RMWUPHA8/
One picture is for exploring symbol from your sketches and the second one is with my propositions. Take your time and let me know what do you think about it :)

(Dandelion's note: I'm pulling out the images as screenshots in GitHub just for archival purposes, in case the invisionapp link goes dead someday.)

![image](https://user-images.githubusercontent.com/1400023/49664716-8a7d9080-fa07-11e8-8452-fd60d99a465e.png)
![image](https://user-images.githubusercontent.com/1400023/49664737-9b2e0680-fa07-11e8-8437-6d68eee5b58c.png)
![image](https://user-images.githubusercontent.com/1400023/49664748-a123e780-fa07-11e8-8d5c-4a5d170eacff.png)
![image](https://user-images.githubusercontent.com/1400023/49664772-ad0fa980-fa07-11e8-8c41-3389d1a6f706.png)

really-by: @akrych

**Comment by teamdandelion** [comment]
@akrych: Thanks again for the work on these logos! Here are my specific thoughts (and I invite other members of the SourceCred community to chime in too!).

## Sun and Sprout Logos
![image](https://user-images.githubusercontent.com/1400023/50860931-1c045900-134c-11e9-8542-bbdd443b20d6.png)
![image](https://user-images.githubusercontent.com/1400023/50863279-047c9e80-1353-11e9-82ec-2a622de3a968.png)

These two are my favorite. I really like the feelings they evoke: sunny optimism and humility. IMO, these logos communicate a lot about the values that we are embedding in the SourceCred project and community. 

I'd be curious to see a few different takes on the sprout in the center -- e.g. what if the sprout had a filled in style rather than line art, or if the sprout were in green. E.g. what if the sprout looked kind of like this one: (from the SustainOSS logo)
![image](https://user-images.githubusercontent.com/1400023/50866484-f896d980-135e-11e9-8d44-411727ac34c3.png)


## Dandelion Graph Logos
![image](https://user-images.githubusercontent.com/1400023/50863387-53c2cf00-1353-11e9-9385-005dfdb86501.png)

![image](https://user-images.githubusercontent.com/1400023/50863610-0e52d180-1354-11e9-862d-1ee8af6deb8d.png)

I really like these logos: they are creative, elegant, and a good fit for SourceCred from a content perspective. SourceCred's approach is to organize projects into graphs (or networks) of contributions, with highly-connected contributions earning more cred. These logos reflect that visually, by showing connections between different entities, often times with the more connected circle being larger. 

## Honorable Mention
This one is really cute :smile:
![image](https://user-images.githubusercontent.com/1400023/50863838-e879fc80-1354-11e9-9351-f520bead6d24.png)

## Conclusion
My focus right now is on building a community around SourceCred: a community that is eager to try to build a really helpful tool for open-source, and optimistic that we can do a great job, while also humble about the pitfalls involved, and that it's going to be a long journey. I think the sun-and-sprout logos do a great job of communicating that, and while the dandelion logos are visually evocative and cool, they don't feel as inviting / don't communicate the values of the project. So, I'd like to move forward with one of the sun-and-sprout logos.

@akrych would you mind mocking a few more variants of the sun-and-sprout logo so we can see what it would look like if the sprout were rendered differently?

**Comment by ajbouh** [comment]
This is really neat exploration overall!

I think the sprout metaphor is great. I don't know how it might be done, but I think the fraction of pixels spent on the sprout should be much more than it is in the current sketches.

Along these lines, I think the value of "nurturing your roots" is an important thing to communicate.

Perhaps there's a way to show that the sprout has some strong connection to something underground?

(Bonus points if the rays coming off the top evoke the idea of the roots attached to the bottom. It might reinforce the recursive and "shoulders of giants" vibe that I get from the vision for sourcecred.)

Hope these comments are helpful!

**Comment by teamdandelion** [comment]
@ajbouh I really like your suggestions. "Nurting your roots" and "shoulders of giants" are great metaphors for SourceCred; as we develop the technical capabilities, there will be a lot of emphasis on flowing cred back to one's dependencies. Also, boosting the visual weight of the sprout makes sense.

Having the rays of light up loop around to being roots at the bottom of the spout would be SO COOL if we can pull it off visually :D.

**Comment by wchargin** [comment]
I’ll chime in, publishing some thoughts that I sent to @decentralion
previously.

When first looking at the sheet of sketches posted earlier, I found
myself really drawn to the leftmost two:

![image](https://user-images.githubusercontent.com/4317806/50873588-71089500-1375-11e9-8a54-e1ee0b55cb87.png)

(and especially the left one above).

If I had to pinpoint why, I’d say that the asymmetry is a big factor,
especially because the design remains balanced as the circle in the
center draws back in the visual center. I also like that the sun and
sprout are kind of _fused_ together rather than merely superimposed.

I also like the sun-with-sprout design that’s been under discussion.
Its proposed vector, especially the first and fourth ones, feel kind of
“heavy” to me in a way that the sketch doesn’t. I don’t want to just
backseat and say “turn down the stroke weight on the outer paths!”, not
least because I don’t know exactly what the solution is, but, like
@decentralion said, I’d be interested to see some more vector
interpretations of this one.

Thanks for the designs so far—excited to see gears turning here!

**Comment by akrych** [comment]
Hello @decentralion 

Here are some more exploration for SourceCred logo inspired "sprout in the center", sun and grow. Let me know what do you think about it! 

https://projects.invisionapp.com/boards/DX3RMWUPHA8/

![sourcecred_logo_artboard 9 3x](https://user-images.githubusercontent.com/22168118/52469355-7bdc6280-2b8b-11e9-91ad-12130aa49487.png)

**Comment by teamdandelion** [comment]
![image](https://user-images.githubusercontent.com/1400023/55030169-2563a000-4fe2-11e9-8337-87b059bf0aac.png)

For tracking, dropping in a cool doodle from [our call] with the Nature 2.0 track w/ the Odyssey Hackathon. I like how it merges the organic and the technical, and having a graph (tree) structure, and maybe the circle behind the tree is a sun?

[our call]: https://www.youtube.com/watch?v=XcaCt3bRcAE

**Comment by teamdandelion** [comment]
During the Odyssey hackathon, we (me + LB + max) came up with an "organic lightbulb" logo concept. The basic idea is a broken lightbulb that has a plant growing in it, and possibly roots sprouting from it. 

The initial inspiration was this drawing:
![image](https://user-images.githubusercontent.com/1400023/56748003-b4054180-6787-11e9-8752-4202a1540102.png)

LB and Max and I were riffing on this, and Max pointed out that a light bulb is kind of an "industrial age" tool for shining light. Effective, but also very regular, commoditized, mass-produced. Whereas SourceCred aspires to be a more organic, "post-industrial" approach to valuing labor. So he suggested: what if the lightbulb were broken, but had a sprout growing from it? And the sprout still shining a light?

Based on that idea, LB drew this canvas:
![image](https://user-images.githubusercontent.com/1400023/56748066-d4350080-6787-11e9-8993-8628125ec19e.png)

And someone on Max's team (Anastasia?) produced this logo:
![image](https://user-images.githubusercontent.com/1400023/56747958-959f4600-6787-11e9-92a5-3af94878385f.png)

I'm quite taken with this idea. I like the combination of metaphors it provides, and that its a visually distinct concept.
